### ISSUE TITLE
When not logged in, redirect to the home page instead of referer page

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/error-reporting-server#100]
I have sometimes experienced this.
I am not logged into the reporting server. Someone has posted a link to a report on github's issue tracker or anywhere else, and I click on it. I am redirected to the original page, like nothing has happened.

A new user might not easily understand what is exactly wrong and that he/she has to login into the reporting server before being able to view that report.

I suggest we redirect to the home page with the flash : `You need to be signed in to do this` visible so that he/she understands clearly why the page is not available. 

What do you think ?

**Comment by nijel** [comment]
Sounds good.
