### ISSUE TITLE
Notifications handling

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#106]
I think notifications needs some rethinking. Seeing 2000 notifications which I have no way to get rid of is not really helping.
- There must be way to get rid of all notifications (so that I can start with clean table).
- Browsing, pagination, sorting and filtering of notifications should work.
- There should be check all function on the notifications page.

**Comment by belwariars** [comment]
@nijel 
Can you please send a screenshot or discuss your problem in a more detailed way ?

**Comment by nijel** [comment]
![notifications_phpmyadmin_-_error_reporting_server_-_2016-01-17_15 24 23](https://cloud.githubusercontent.com/assets/212189/12377921/6824cf80-bd2e-11e5-8c19-3ad39bf81560.png)

**Comment by ibennetch** [comment]
Perhaps the ability to drop reports for old/unsupported phpMyAdmin versions would also help?

**Comment by nijel** [comment]
Not sure if it's good idea, the issue might be still there... Anyway this issue is about notifications, which is quite separate topic from handling reports :-).

**Comment by ibennetch** [comment]
Fair enough :)

**Comment by ibennetch** [comment]
Fair enough :)
