### ISSUE TITLE
Collect user languages

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#109]
This is server side counterpart for https://github.com/phpmyadmin/phpmyadmin/issues/11790

We should collect reported user interface language and show that in stats.

**Comment by ujjwalwahi** [comment]
@nijel 
Hi, I would like to work on this.

As I understand this issue, locale information is present in incident table, now we require to display it in stats and reports page

Please correct me if I am wrong.

**Comment by nijel** [comment]
Yes - It is in the incident table, it's shown on incident table, but is missing from the stats and error report page.

**Comment by ujjwalwahi** [comment]
Hi @nijel 
Please have a look at my merge request.

**Comment by devenbansod** [comment]
@nijel : I think the migrations in the PR have to be run on the reporting server. It's showing an internal error.

**Comment by nijel** [comment]
I've executed them, it just needed some time:

```

Welcome to CakePHP v3.1.6 Console
---------------------------------------------------------------
App : src
Path: /home/reports/error-reporting-server/src/
PHP : 5.6.14-0+deb8u1
---------------------------------------------------------------
using migration path /home/reports/error-reporting-server/config/Migrations
using environment default
using adapter mysql
using database reports

 == 20160111023543 AddLocaleToIncidents: migrating
 == 20160111023543 AddLocaleToIncidents: migrated 2519.8206s

All Done. Took 2519.9032s
```
