### ISSUE TITLE
HTTP Link in 'error-reporting-server' comments

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/error-reporting-server#127]
As reported by Emanuel Bronshtein,

in:
    https://github.com/phpmyadmin/phpmyadmin/issues/12622#issuecomment-254249291
This comment is posted automatically by phpMyAdmin's <a href="http://reports.phpmyadmin.net">error-reporting-server</a>.

fix:
    change http://reports.phpmyadmin.net to https://reports.phpmyadmin.net

**Comment by nijel** [comment]
Already fixed in 5091ebdb549c4ef42d4de1dee351c3ae294a583b (but obviously this affects only new reports).
