### ISSUE TITLE
Failure on cleaning old notifications

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#139]
This happens for last week or so on the production:

```

Welcome to CakePHP v3.4.6 Console
---------------------------------------------------------------
App : src
Path: /home/reports/error-reporting-server/src/
PHP : 7.0.16-3
---------------------------------------------------------------
2017-05-09 08:11:58 Error: FAILED: Deleting older Notifications!!
```

I've tried to run the generated SQL query manually and it works just fine...

**Comment by devenbansod** [comment]
I think this is could be because no notifications were deleted. I have made a PR at #143 to display better informational/error messages on running the shell.

**Comment by nijel** [comment]
That explains it, in 2.x the semantics was different - https://book.cakephp.org/2.0/en/models/deleting-data.html#deleteall
