### ISSUE TITLE
Empty state when reporting issue to GitHub

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#158]
It seems the state synchronization doesn't do the right thing when creating new issues in GitHub as it did set empty state (https://reports.phpmyadmin.net/reports/view/33415).

**Comment by devenbansod** [comment]
Sorry, but I think I am unable to understand this completely. 

Is it: We link a report by creating a new issue. Then we receive a web-hook event for this issue, and we are setting the status as blank. ?

OR is it related to linking it with already existing issue?
OR is it related to listening to the closing of a linked-issue on Github?

**Comment by nijel** [comment]
Sorry for not being clear enough.

Before creating the GitHub issue the state is "New":

![screenshot-2017-6-15 reports phpmyadmin - error reporting server](https://user-images.githubusercontent.com/212189/27187464-93ef4192-51eb-11e7-931c-32682a8ce52e.png)

It stays so immediately after creating the GitHub issue, however as soon as the notification arrives it is changed to empty:

![screenshot-2017-6-15 reports phpmyadmin - error reporting server - after](https://user-images.githubusercontent.com/212189/27187430-7fc0b1e2-51eb-11e7-98c4-7af7c3eb773e.png)

**Comment by nijel** [comment]
Seems to be fixed by #162.
