### ISSUE TITLE
Avoid processing resolved issues when checking GitHub status

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#165]
IMHO we should avoid processing resolved issues when checking GitHub status. The resolved issues will most likely not be reopened, so this is just wasting resources on both our and GitHub side.

**Comment by devenbansod** [comment]
This makes sense. I did not put the conditional check on report status just to make sure that actually everything is put literally in 'sync' with Github. 
But given our operational inputs that we seldom re-open a closed issue which is linked to a error report, it makes sense to put an extra condition not to run this job for `resolved` status reports and thus avoid making unnecessary calls.
