### ISSUE TITLE
Designer view Fatal Javascript Error and Error Reporting not submitting

### ISSUE THREAD

**Issue by alexmiller00** [phpmyadmin/error-reporting-server#180]
WAMP(PC) localhost JS fatal error happens on XAMPP(PC) and MAMP(OSX) this error has been happening for quite some time, it is when you try to access the designer view of any db. I would like to be able to use this function, I have also experienced it on other platforms such as digitalocean's one click phpmyadmin install droplet.

See Error below...
{
  
  "pma_version": "4.8.3",
    "browser_name": "CHROME",
    "browser_version": "70.0.3538.102",
    "user_os": "Win",
    "server_software": "Apache/2.4.35 (Win64) PHP/7.2.10",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.2.10",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'style' of null",
        "stack": [
            {
                "line": "292",
                "func": "",
                "column": "",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "Main",
                "line": "265",
                "column": "42",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.",
                "line": "38",
                "column": "5",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.new_func",
                "line": "248",
                "column": "33",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.dispatch",
                "line": "2",
                "column": "41772",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.$event.dispatch",
                "line": "374",
                "column": "19",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.y.handle",
                "line": "2",
                "column": "39791",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "Object.trigger",
                "line": "2",
                "column": "69551",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.",
                "line": "2",
                "column": "70146",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "Function.each",
                "line": "2",
                "column": "2573",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "jQuery.fn.init.each",
                "line": "2",
                "column": "1240",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}

**Comment by williamdes** [comment]
@alexmiller00 Thank you for the report, please post it on https://github.com/phpmyadmin/phpmyadmin
I m sure that I have already seen your issue somewhere ! 
Closing since this is not the right repo for phpmyadmin issues.
