### ISSUE TITLE
Github access_token query parameter deprecation

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/error-reporting-server#184]
Github is deprecating the use of `access_token` as a query parameter. According to the logs, we're using that at some point in error-reporting-server. Their suggested solutions are at https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param (mostly to pass it as a header value rather than query string).

I believe based on the log reports that the query is hitting the https://api.github.com/user endpoint.

**Comment by williamdes** [comment]
Fixed ;)
