### ISSUE TITLE
Error when auto-reporting error

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/error-reporting-server#185]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/relation&db=sakila&table=inventory&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure

> Report was created but couldn't be send. Please report manually.

![pma](https://user-images.githubusercontent.com/2218936/69492191-54971d80-0e9f-11ea-92b7-75adfbd1ca76.PNG)

**Comment by williamdes** [comment]
On my workstation it now works fine. Will confirm that when the server deploys my code.
