### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/error-reporting-server#186]
@williamdes I think this is what you were asking about on Gitter.

> 2021-03-15 01:53:22 Error: [InvalidArgumentException] The value passed for the "$name" argument must be either a string, or an object, NULL given. in /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Mailer/Mailer.php on line 487
> Stack Trace:
> - /home/reports/error-reporting-server/src/Controller/Component/MailerComponent.php:51
> - /home/reports/error-reporting-server/src/Controller/IncidentsController.php:163
> - /home/reports/error-reporting-server/src/Controller/IncidentsController.php:95
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Controller/Controller.php:531
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:151
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/BaseApplication.php:313
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Runner.php:77
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:161
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Runner.php:73
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Runner.php:73
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:126
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Runner.php:73
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Runner.php:58
> - /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Http/Server.php:90
> - /home/reports/error-reporting-server/webroot/index.php:40
> 
> Request URL: /incidents/create
> Client IP: `xxx.xxx.xxx.xx`

**Comment by williamdes** [comment]
@ibennetch does `app.php` have this keys in the file ?
```php

    'NotificationEmailsTo' => 'williamdes+phpmyadmin-error-reports@xxxxxx.xxxxxxx',
    'NotificationEmailsFrom' => 'mail+phpmyadmin-error-reports@xxxxxx.xxxxxx',
    'NotificationEmailsTransport' => 'default',
```

**Comment by williamdes** [comment]
my config is 
```php
    'EmailTransport' => [
        'default' => [
            'className' => SmtpTransport::class,
            // The following keys are used in SMTP transports
            'host' => 'mail.xxxxxxxxxx.xxxx',
            'port' => 587,
            'timeout' => 30,
            'username' => 'mail@xxxxxx.xxxxxx',
            'password' => 'xxxxxxxxxxxxxxxx',
            'client' => null,
            'tls' => true,
            'keepAlive' => true,
        ],
        'test' => [
            'className' => DebugTransport::class,
        ],
    ],
```

**Comment by ibennetch** [comment]
```
    'NotificationEmailsTo' => 'reports-notify@phpmyadmin.xxx',
    'NotificationEmailsFrom' => 'reports-notify@phpmyadmin.xxx',
```

NotificationEmailsTransport is not defined.

reports-notify doesn't seem to go anywhere, though, so I'm unclear about this. There's no mail alias for that specific address, but as far as I know that hasn't been changed in a very, very long time.

**Comment by williamdes** [comment]
> ```
>     'NotificationEmailsTo' => 'reports-notify@phpmyadmin.xxx',
>     'NotificationEmailsFrom' => 'reports-notify@phpmyadmin.xxx',
> ```
> 
> NotificationEmailsTransport is not defined.
> 
> reports-notify doesn't seem to go anywhere, though, so I'm unclear about this. There's no mail alias for that specific address, but as far as I know that hasn't been changed in a very, very long time.

I pushed a commit to handle a bad configuration.
If possible I would like to receive notifications about error-reports. Maybe a new mailing list would be usefull.
I think you should set `NotificationEmailsTransport` to `default`
