### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/error-reporting-server#187]
I receive a 502 Bad Gateway error when trying to log in to https://reports.phpmyadmin.net/.

It used to work (last year).

**Comment by ibennetch** [comment]
Thanks, we will take a look.

**Comment by ibennetch** [comment]
Could you please try again? I've restarted the FPM process, which seems to have hung somehow, and it seems to work for me now.

Many thanks for the report.

**Comment by liviuconcioiu** [comment]
It works!
