### ISSUE TITLE
Reports not showing

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/error-reporting-server#188]
@williamdes reports aren't showing on [https://reports.phpmyadmin.net/reports](https://reports.phpmyadmin.net/reports). Json response is empty.

![reporting](https://user-images.githubusercontent.com/25424343/211948190-f4cb70da-d92b-4bf7-8ae4-5c31fa4a37a6.png)

**Comment by williamdes** [comment]
Thank you for the ping, I will have a look
I am planning to shut down the instance and forward reports to an internal Sentry instance

**Comment by williamdes** [comment]
Fixed 🎉
