### ISSUE TITLE
Merge OS stats

### ISSUE THREAD

**Issue by roccivic** [phpmyadmin/error-reporting-server#22]
On the stats page (http://reports.phpmyadmin.net/stats), Win and Windows are reported as different platforms, but I guess that these should be counted together.

**Comment by devenbansod** [comment]
Is this still present ?

I guess this should not be present now since we set it only here : https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Config.php#L169 and use the same value while filing an incident of a report.

Any ideas ?

**Comment by nijel** [comment]
Indeed the original issue for OS stats is indeed fixed.
