### ISSUE TITLE
Remember entries per page

### ISSUE THREAD

**Issue by ZweiSteinSoft** [phpmyadmin/error-reporting-server#25]
The report list can show a variable number of report entries per page. When navigating away (like to "Stats"), the setting is not restored on returning to the report list. I suggest the reporting server save the setting in either a cookie or a user-based storage on the server.

**Comment by zixtor** [comment]
PR https://github.com/phpmyadmin/error-reporting-server/pull/88 should achieve this.

**Comment by zixtor** [comment]
@nijel Should we close this issue? Also, at https://wiki.phpmyadmin.net/pma/GSoC_2016_Ideas_List#Error_reporting_server, I think "Maintaining state and microhistory" should be removed from expected improvements list, instead "Persistent settings per user" #69 could be listed there.
