### ISSUE TITLE
Assign existing SF.net issue

### ISSUE THREAD

**Issue by ZweiSteinSoft** [phpmyadmin/error-reporting-server#26]
When viewing a report, there is a link to submit the issue to SourceForge. I suggest there be another function to enter the ID of an existing SF.net bug report. When submitting, this feature should post a comment on that issue, containing the reporting server link and related automated information, as posting a new bug issue would contain. Other fields of the existing issue should not be modified, though.

**Comment by nijel** [comment]
This is already there (though we're using GitHub issue tracking now).
