### ISSUE TITLE
Provide email notification for new reports

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#31]
Currently, new reports are not well handled. Having email notifications going to our bugs list might improve the situation.

**Comment by zaverichintan** [comment]
Hey, is this issue solved?

**Comment by devenbansod** [comment]
Hi @zaverichintan , I don't think it is fully implemented yet. 
There is a working Notifications page (which also needs an overhaul in #106), but 'Email notifications' for new reports is, as far as I know, not implemented yet.

**Comment by nijel** [comment]
Yes, there are no email notifications. However I'm not really sure about whether this will be really useful in the end with amount of errors we currently see...
