### ISSUE TITLE
Wrong line numbers in stacktrace

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#63]
The line numbers in stractrace always start with 1 but not with the real line numbers...

https://reports.phpmyadmin.net/reports/view/3131

**Comment by devenbansod** [comment]
I am slightly confused about how to do it for the JS reports, since there is a context and how should we know the starting line number of this context ? Since the Line number provided in the stacktrace will be line number of the line with an error right ?
Am I going wrong somewhere ?

**Comment by nijel** [comment]
Isn't the context length fixed? Actually with javascript this is more annoying than with PHP as there is no clue where the problematic code is (you can guess it's in the middle...). Also highlighting the line would be great...
