### ISSUE TITLE
$cfg['Servers'][$i]['favorite'] ...	not OK Persistent favorite tables: Disabled

### ISSUE THREAD

**Issue by pvanbavel** [phpmyadmin/error-reporting-server#75]
$cfg['Servers'][$i]['favorite'] ...	not OK
Persistent favorite tables: Disabled

Is the message I get when starting PHPmyAdmin 4.3.8.

1) This line has been added to config.inc.php
    $cfg['Servers'][$i]['favorite']         = 'pma__favorite';

2) The table has been created.

3) In the documentation I cannot find the following line
    $cfg['Servers'][$i]['favorite']         = 'pma__favorite';

So what do I need to do to get rid of the message 
    $cfg['Servers'][$i]['favorite'] ...	not OK
    Persistent favorite tables: Disabled

**Comment by lem9** [comment]
For support, visit http://phpmyadmin.net and click Support.

**Comment by nijel** [comment]
This is not bug in error reporting server, but phpMyAdmin itself, please report bug in correct place.
