### ISSUE TITLE
cntrl-click opens the report both in current tab and a new tab

### ISSUE THREAD

**Issue by smita786** [phpmyadmin/error-reporting-server#85]
In Marc's <@lem9> words:
let's say I choose a PMA version then ctrl-click one of the reports, I would expect the UI to open a new browser tab and put just this report inside it. That's what happens, but in both browser tabs. Therefore I lose in the first tab my context, and if I click the back button in the first tab I lose the PMA version I had chosen.

**Comment by zixtor** [comment]
PR: https://github.com/phpmyadmin/error-reporting-server/pull/88
