### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by Hannobal** [phpmyadmin/error-reporting-server#92]
Please update the links in the tracker section at https://www.phpmyadmin.net/support/

**Comment by zixtor** [comment]
@Hannobal The links are correct, but seems like SourceForge is down right now. See https://twitter.com/sfnet_ops/status/621859945487581184

**Comment by Hannobal** [comment]
Why not moving to Github?

**Comment by nijel** [comment]
We're moving, but it's not yet completed (we have some problem with importing existing issues to GitHub, waiting for GitHub support to resolve this). Once we will use issue tracker here for phpMyAdmin issues, the links will be updated.

This repository is for error reporting server.
